// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as SqliteTypes } from '@prisma/orm-sqlite/adapter/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-sqlite/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-sqlite/contract/types';

export type StorageHash =
  StorageHashBase<'7df87d7dd87f20168e7aed846c24e8df693edf7dc1cd083cad2e06b2fafce568'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'260b8608d1aacaf1f690779a6cff39a12947c599597c5ba464ca75b9e775df53'>;

export type CodecTypes = SqliteTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = Record<string, never>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/real@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'sqlite/bigint@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'sqlite/bigint@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/blob@1': { readonly output: 'sqlite/blob@1'; readonly nullable: true };
      readonly 'sqlite/datetime@1': {
        readonly output: 'sqlite/datetime@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/integer@1'; readonly nullable: true };
      readonly 'sqlite/json@1': { readonly output: 'sqlite/json@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/text@1': { readonly output: 'sqlite/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/blob@1': { readonly output: 'sqlite/blob@1'; readonly nullable: true };
      readonly 'sqlite/datetime@1': {
        readonly output: 'sqlite/datetime@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/integer@1'; readonly nullable: true };
      readonly 'sqlite/json@1': { readonly output: 'sqlite/json@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/text@1': { readonly output: 'sqlite/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'sql/int@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigint@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly Card: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly userId: CodecTypes['sqlite/text@1']['output'];
      readonly title: CodecTypes['sqlite/text@1']['output'];
      readonly question: CodecTypes['sqlite/text@1']['output'];
      readonly answer: CodecTypes['sqlite/text@1']['output'];
      readonly topic: CodecTypes['sqlite/text@1']['output'];
      readonly tags: CodecTypes['sqlite/text@1']['output'];
      readonly status: CodecTypes['sqlite/text@1']['output'];
    };
    readonly User: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly email: CodecTypes['sqlite/text@1']['output'];
      readonly password: CodecTypes['sqlite/text@1']['output'];
      readonly username: CodecTypes['sqlite/text@1']['output'];
      readonly avatarUrl: CodecTypes['sqlite/text@1']['output'] | null;
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly Card: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly userId: CodecTypes['sqlite/text@1']['input'];
      readonly title: CodecTypes['sqlite/text@1']['input'];
      readonly question: CodecTypes['sqlite/text@1']['input'];
      readonly answer: CodecTypes['sqlite/text@1']['input'];
      readonly topic: CodecTypes['sqlite/text@1']['input'];
      readonly tags: CodecTypes['sqlite/text@1']['input'];
      readonly status: CodecTypes['sqlite/text@1']['input'];
    };
    readonly User: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly email: CodecTypes['sqlite/text@1']['input'];
      readonly password: CodecTypes['sqlite/text@1']['input'];
      readonly username: CodecTypes['sqlite/text@1']['input'];
      readonly avatarUrl: CodecTypes['sqlite/text@1']['input'] | null;
    };
  };
};
export type StorageColumnTypes = {
  readonly __unbound__: {
    readonly card: {
      readonly answer: CodecTypes['sqlite/text@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly question: CodecTypes['sqlite/text@1']['output'];
      readonly status: CodecTypes['sqlite/text@1']['output'];
      readonly tags: CodecTypes['sqlite/text@1']['output'];
      readonly title: CodecTypes['sqlite/text@1']['output'];
      readonly topic: CodecTypes['sqlite/text@1']['output'];
      readonly userId: CodecTypes['sqlite/text@1']['output'];
    };
    readonly user: {
      readonly avatarUrl: CodecTypes['sqlite/text@1']['output'] | null;
      readonly email: CodecTypes['sqlite/text@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly password: CodecTypes['sqlite/text@1']['output'];
      readonly username: CodecTypes['sqlite/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly __unbound__: {
    readonly card: {
      readonly answer: CodecTypes['sqlite/text@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly question: CodecTypes['sqlite/text@1']['input'];
      readonly status: CodecTypes['sqlite/text@1']['input'];
      readonly tags: CodecTypes['sqlite/text@1']['input'];
      readonly title: CodecTypes['sqlite/text@1']['input'];
      readonly topic: CodecTypes['sqlite/text@1']['input'];
      readonly userId: CodecTypes['sqlite/text@1']['input'];
    };
    readonly user: {
      readonly avatarUrl: CodecTypes['sqlite/text@1']['input'] | null;
      readonly email: CodecTypes['sqlite/text@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly password: CodecTypes['sqlite/text@1']['input'];
      readonly username: CodecTypes['sqlite/text@1']['input'];
    };
  };
};

export namespace Models {
  export type User = {
    id: CodecTypes['sqlite/text@1']['output'];
    email: CodecTypes['sqlite/text@1']['output'];
    password: CodecTypes['sqlite/text@1']['output'];
    username: CodecTypes['sqlite/text@1']['output'];
    avatarUrl: CodecTypes['sqlite/text@1']['output'] | null;
    cards: Card[];
    readonly [RelationKeys]?: 'cards';
  };
  export type Card = {
    id: CodecTypes['sqlite/text@1']['output'];
    userId: CodecTypes['sqlite/text@1']['output'];
    title: CodecTypes['sqlite/text@1']['output'];
    question: CodecTypes['sqlite/text@1']['output'];
    answer: CodecTypes['sqlite/text@1']['output'];
    topic: CodecTypes['sqlite/text@1']['output'];
    tags: CodecTypes['sqlite/text@1']['output'];
    status: CodecTypes['sqlite/text@1']['output'];
    user: User;
    readonly [RelationKeys]?: 'user';
  };
}

export declare const models: {
  User: Models.User;
  Card: Models.Card;
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'sqlite-namespace';
        readonly entries: {
          readonly table: {
            readonly card: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly question: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly answer: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly topic: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly tags: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/text@1', 'published'>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'card_userId_idx_a489d58a';
                  readonly prefix: 'card_userId_idx';
                  readonly columns: readonly ['userId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'card';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly user: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly password: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly username: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly avatarUrl: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'sqlite';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly user: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'User' };
    readonly card: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Card' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly Card: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly question: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly answer: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly topic: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly tags: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'card';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'userId' };
                readonly title: { readonly column: 'title' };
                readonly question: { readonly column: 'question' };
                readonly answer: { readonly column: 'answer' };
                readonly topic: { readonly column: 'topic' };
                readonly tags: { readonly column: 'tags' };
                readonly status: { readonly column: 'status' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly password: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly username: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly avatarUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
            };
            readonly relations: {
              readonly cards: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Card';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'user';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly email: { readonly column: 'email' };
                readonly password: { readonly column: 'password' };
                readonly username: { readonly column: 'username' };
                readonly avatarUrl: { readonly column: 'avatarUrl' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly sql: {
      readonly enums: false;
      readonly foreignKeys: true;
      readonly jsonAgg: true;
      readonly lateral: false;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
